fix(docs): update jiva migration docs with affinity changes
openebs/upgrade pull request #129
Opened 2021-08-30 14:03 UTC by shubham14bajpai

Signed-off-by: shubham <shubham14bajpai@gmail.com>

**What this PR does**:
Updates the jiva volume migration docs. Currently tested on ci images. Will update the PR status once newly tagged images are available.
**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] PR messages has document related information
- [ ] Labelled this PR & related issue with `documentation` tag
- [ ] PR messages has breaking changes related information
- [ ] PR messages has upgrade related information
- [ ] Labelled this PR & related issue with `requires-upgrade` tag
- [ ] Tests updated

2021-09-07 07:04 UTC, nsathyaseelan requested changes

2021-09-07 07:04 UTC, nsathyaseelan commented on docs/migration.md
> + For this example lets say the original volume has PVC name `demo-vol-claim` and PV name `pvc-feefe71b-d073-4f0d-a5c2-bc0b78812683`.
Include a note volume provisioned in default namespace

2021-09-07 07:04 UTC, nsathyaseelan commented on docs/migration.md
>      ```sh
Post this PVC deletion seeing older PV still in released state can we include step to clear this as well

2021-09-07 07:20 UTC, nsathyaseelan approved these changes
lgtm

2021-09-08 06:16 UTC, prateekpandey14 commented on docs/migration.md
> +    $ k get pods -o wide
we can use pv-name label just to differentiate with other pods on per volume bases , helpful for the user to understand the no of pods ?

2021-09-08 06:20 UTC, prateekpandey14 reviewed
minor comment otherwise looks good

2021-09-08 08:56 UTC, prateekpandey14 approved these changes

2021-09-08 08:56 UTC, merged