chore : Added PR and Issue template
openebs/upgrade pull request #54
Opened 2020-10-01 01:42 UTC by Hard-Coder05

This PR solves the issue: https://github.com/openebs/openebs/issues/3144

2020-10-01 05:22 UTC, shubham14bajpai requested changes
Gave a few comments

2020-10-01 05:22 UTC, shubham14bajpai commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* `kubectl get pods -n <openebs_namespace>`
```suggestion
* `kubectl get pods -n <openebs_namespace> --show-labels`
* `kubectl logs <upgrade_job_pod> -n <openebs_namespace>`
```

2020-10-01 05:22 UTC, shubham14bajpai commented on .github/ISSUE_TEMPLATE/feature-request.md
> +about: Suggest an idea to improve cstor-csi driver
```suggestion
about: Suggest an idea to improve openebs upgrades
```

2020-10-02 11:17 UTC, shubham14bajpai approved these changes
LGTM

2020-10-04 06:27 UTC, Hard-Coder05 commented
@shubham14bajpai @prateekpandey14 As the changes are aproved Please merge the PR!

2020-10-04 13:06 UTC, prateekpandey14 approved these changes
lgtm

2020-10-04 13:07 UTC, merged

2020-10-05 16:26 UTC, prateekpandey14 commented
Thank you @Hard-Coder05  for this PR. You can sign up for Hacktoberfest swag from MayaData by entering details here: https://github.com/mayadata-io/swag/issues/new/choose

2020-10-05 17:00 UTC, Hard-Coder05 commented
@prateekpandey14 I have a doubt! The contribution detail form had no option for T-Shirt size btw!

2020-10-06 11:36 UTC, prateekpandey14 commented
ahh , added the size option